### ISSUE TITLE
environment install

### ISSUE THREAD

**Issue by msra-jqxu** [facebookresearch/DepthContrast#23]
Hi, I use:
conda create --name <env> --file requirements.txt -c intel
to install environment. But  there are a lot of conflicts. Do you know how to resolve it?
![image](https://user-images.githubusercontent.com/53702716/126507652-05850cac-77d7-4c76-adc3-db95ab9c1de0.png)

**Comment by zaiweizhang** [comment]
For this project, we use CUDA version 10.1. I would suggest you change your cuda version.

**Comment by msra-jqxu** [comment]
I changed cuda version to 10.1, but it doesn't work. And my friends meet the same problem too. 
I also refered to https://github.com/facebookresearch/DepthContrast/issues/7. 
The conda environment file(yaml file) still causes package conflicts.

**Comment by zaiweizhang** [comment]
Would you mind posting the conflicts here? @imisra We directly created the yaml file from a working environment, right? Can you think of anything that would cause the issues?

**Comment by imisra** [comment]
@msra-jqxu - can you try the requirements file here (from the initial commit) -- https://github.com/facebookresearch/DepthContrast/blob/46b9cbbc5546d6c6795e267d06d9c2af1fcf1781/requirements.txt

The recent requirements file was updated to latest versions of packages due to security vulnerabilities. This may lead to package conflicts.

**Comment by msra-jqxu** [comment]
I successfully installed the environment. Thank you two very much!
