### ISSUE TITLE
Can I ask you for data?

### ISSUE THREAD

**Issue by JeonMinkyu** [facebookresearch/DepthContrast#6]
Hi, 

I highly appreciate you for sharing the code. 
It seems that the entire data(ScanNet) take up about 1.2 TB to fully download, and I was wondering if you could share the specific data you employed during your experiment? 

Please let me know if you have any question or concern and I am looking forward to hearing back from you.
Thank you,

**Comment by imisra** [comment]
Hi @JeonMinkyu ,

Unfortunately, we cannot share the ScanNet data since it is not collected by us. You will have to sign the terms of use for ScanNet at http://kaldir.vc.in.tum.de/scannet/ScanNet_TOS.pdf and download the data yourself.

For the pretraining task, we extracted ~190K depth maps from the ~1200 training videos.
